services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blockchain
      POSTGRES_USER: blockchain
      POSTGRES_PASSWORD: blockchain
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && gunicorn blockchain.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: